spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center?serverTimezone=Asia/Shanghai
    hikari:
      username: root
      password: 123456
      # >= 6.x: com.mysql.cj.jdbc.Driver
      # <= 5.x: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: user-center
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        cluster-name: NJ
    sentinel:
      transport:
        dashboard: localhost:8080
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
      bindings:
        input:
          destination: add-bonus
          group: binder-group
server:
  port: 8081
logging:
  level:
    com.alibaba.nacos: error
#rocketmq:
#  name-server: 127.0.0.1:9876
#  producer:
#    group: test-group
jwt:
  secret: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
  # 有效期，单位秒，默认2周
  expire-time-in-second: 1209600